apiVersion: v1
data:
  envoy.yaml: "layered_runtime:\n  layers:\n  - name: static_layer\n    static_layer:\n
    \     envoy.reloadable_features.enable_deprecated_v2_api: true\n      envoy.reloadable_features.disable_tls_inspector_injection:
    false\n      overload:\n        global_downstream_max_connections: 250000\n      upstream:\n
    \       healthy_panic_threshold:\n          value: 50\n  - name: admin_layer\n
    \   admin_layer: {}\nnode:\n  cluster: gateway\n  id: \"{{.PodName}}.{{.PodNamespace}}\"\n
    \ metadata:\n    # role's value is the key for the in-memory xds cache (projects/gloo/pkg/xds/envoy.go)\n
    \   role: \"{{.PodNamespace}}~gateway-proxy\"\nstatic_resources:\n  listeners:
    \ \n    - name: prometheus_listener\n      address:\n        socket_address:\n
    \         address: 0.0.0.0\n          port_value: 8081\n      filter_chains:\n
    \       - filters:\n            - name: envoy.filters.network.http_connection_manager\n
    \             typed_config:\n                \"@type\": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager\n
    \               codec_type: AUTO\n                stat_prefix: prometheus\n                stream_idle_timeout: 0s\n                route_config:\n
    \                 name: prometheus_route\n                  virtual_hosts:\n                    -
    name: prometheus_host\n                      domains:\n                        -
    \"*\"\n                      routes:\n                        - match:\n                            path:
    \"/ready\"\n                            headers:\n                            -
    name: \":method\"\n                              exact_match: GET\n                          route:\n
    \                           cluster: admin_port_cluster\n                        -
    match:\n                            prefix: \"/metrics\"\n                            headers:\n
    \                           - name: \":method\"\n                              exact_match:
    GET\n                          route:\n                            prefix_rewrite:
    /stats/prometheus\n                            cluster: admin_port_cluster\n                http_filters:\n
    \                 - name: envoy.filters.http.router  \n  clusters:\n  - name:
    gloo.gloo-system.svc.cluster.local:9977\n    alt_stat_name: xds_cluster\n    connect_timeout:
    5.000s\n    load_assignment:\n      cluster_name: gloo.gloo-system.svc.cluster.local:9977\n
    \     endpoints:\n      - lb_endpoints:\n        - endpoint:\n            address:\n
    \             socket_address:\n                address: gloo.gloo-system.svc.cluster.local\n
    \               port_value: 9977\n    http2_protocol_options: {}\n    upstream_connection_options:\n
    \     tcp_keepalive: {}\n    type: STRICT_DNS\n    respect_dns_ttl: true\n  -
    name: rest_xds_cluster\n    alt_stat_name: rest_xds_cluster\n    connect_timeout:
    5.000s\n    load_assignment:\n      cluster_name: rest_xds_cluster\n      endpoints:\n
    \     - lb_endpoints:\n        - endpoint:\n            address:\n              socket_address:\n
    \               address: gloo.gloo-system.svc.cluster.local\n                port_value:
    9976\n    upstream_connection_options:\n      tcp_keepalive: {}\n    type: STRICT_DNS\n
    \   respect_dns_ttl: true\n  - name: wasm-cache\n    connect_timeout: 5.000s\n
    \   load_assignment:\n      cluster_name: wasm-cache\n      endpoints:\n      -
    lb_endpoints:\n        - endpoint:\n            address:\n              socket_address:\n
    \               address: gloo.gloo-system.svc.cluster.local\n                port_value:
    9979\n    upstream_connection_options:\n      tcp_keepalive: {}\n    type: STRICT_DNS\n
    \   respect_dns_ttl: true   \n  - name: admin_port_cluster\n    connect_timeout:
    5.000s\n    type: STATIC\n    lb_policy: ROUND_ROBIN\n    load_assignment:\n      cluster_name:
    admin_port_cluster\n      endpoints:\n      - lb_endpoints:\n        - endpoint:\n
    \           address:\n              socket_address:\n                address:
    127.0.0.1\n                port_value: 19000 \n\ndynamic_resources:\n  ads_config:\n
    \   transport_api_version: V3\n    api_type: GRPC\n    rate_limit_settings: {}\n
    \   grpc_services:\n    - envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9977}\n
    \ cds_config:\n    resource_api_version: V3\n    ads: {}\n  lds_config:\n    resource_api_version:
    V3\n    ads: {}\nadmin:\n  access_log_path: /dev/null\n  address:\n    socket_address:\n
    \     address: 127.0.0.1\n      port_value: 19000\n"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo-system
  creationTimestamp: "2021-04-22T19:47:07Z"
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:envoy.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:gateway-proxy-id: {}
          f:gloo: {}
    manager: Go-http-client
    operation: Update
    time: "2021-04-22T19:47:07Z"
  name: gateway-proxy-envoy-config
  namespace: gloo-system
  resourceVersion: "1502"
  selfLink: /api/v1/namespaces/gloo-system/configmaps/gateway-proxy-envoy-config
  uid: 85785733-404b-4827-a2ea-f0cfc214bd31
