apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: google-oidc
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        app_url: http://localhost:8080
        callback_path: /callback
        client_id: 967359009029-rkfgu49os1hbtsfono7i1di3igpkuhio.apps.googleusercontent.com
        client_secret_ref:
          name: google
          namespace: gloo-system
        issuer_url: https://accounts.google.com
        scopes:
        - email
        session:
          cookieOptions:
            notSecure: true
            maxAge: 3600
          failOnFetchFailure: true
          redis:
            cookieName: cookie
            options:
              host: redis.gloo-system.svc.cluster.local:6379
        logoutPath: /logout