apiVersion: devportal.solo.io/v1alpha1
kind: Environment
metadata:
  name: dev
  namespace: default
spec:
  apiProducts:
  - name: petstore-product
    namespace: default
    publishedVersions:
    - name: v1
  displayInfo:
    description: This environment is meant for developers to deploy and test their
      APIs.
    displayName: Development
  domains:
  - api.example.com
  - api.example.com:32000

